/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};


/// struct for typed errors of method [`gasless_get_price`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GaslessGetPriceError {
    Status400(models::GaslessGetPrice400Response),
    Status422(models::SwapPermit2GetPrice422Response),
    Status500(models::SwapPermit2GetPrice500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`gasless_get_quote`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GaslessGetQuoteError {
    Status400(models::GaslessGetQuote400Response),
    Status422(models::SwapPermit2GetPrice422Response),
    Status500(models::SwapPermit2GetPrice500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`gasless_get_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GaslessGetStatusError {
    Status400(models::InputInvalid),
    Status404(models::MetaTransactionStatusNotFound),
    Status500(models::SwapPermit2GetPrice500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`gasless_submit`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GaslessSubmitError {
    Status400(models::GaslessSubmit400Response),
    Status500(models::SwapPermit2GetPrice500Response),
    UnknownValue(serde_json::Value),
}


/// Get the indicative price for a gasless swap
pub async fn gasless_get_price(configuration: &configuration::Configuration, param_0x_api_key: &str, chain_id: i32, buy_token: &str, sell_token: &str, sell_amount: &str, param_0x_version: Option<&str>, taker: Option<&str>, swap_fee_recipient: Option<&str>, swap_fee_bps: Option<i32>, swap_fee_token: Option<&str>, trade_surplus_recipient: Option<&str>, excluded_sources: Option<&str>) -> Result<models::GaslessGetPrice200Response, Error<GaslessGetPriceError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/gasless/price", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("chainId", &chain_id.to_string())]);
    local_var_req_builder = local_var_req_builder.query(&[("buyToken", &buy_token.to_string())]);
    local_var_req_builder = local_var_req_builder.query(&[("sellToken", &sell_token.to_string())]);
    local_var_req_builder = local_var_req_builder.query(&[("sellAmount", &sell_amount.to_string())]);
    if let Some(ref local_var_str) = taker {
        local_var_req_builder = local_var_req_builder.query(&[("taker", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = swap_fee_recipient {
        local_var_req_builder = local_var_req_builder.query(&[("swapFeeRecipient", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = swap_fee_bps {
        local_var_req_builder = local_var_req_builder.query(&[("swapFeeBps", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = swap_fee_token {
        local_var_req_builder = local_var_req_builder.query(&[("swapFeeToken", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = trade_surplus_recipient {
        local_var_req_builder = local_var_req_builder.query(&[("tradeSurplusRecipient", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = excluded_sources {
        local_var_req_builder = local_var_req_builder.query(&[("excludedSources", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    local_var_req_builder = local_var_req_builder.header("0x-api-key", param_0x_api_key.to_string());
    if let Some(local_var_param_value) = param_0x_version {
        local_var_req_builder = local_var_req_builder.header("0x-version", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GaslessGetPriceError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Get the firm quote for a gasless swap
pub async fn gasless_get_quote(configuration: &configuration::Configuration, param_0x_api_key: &str, chain_id: i32, buy_token: &str, sell_token: &str, sell_amount: &str, taker: &str, param_0x_version: Option<&str>, swap_fee_recipient: Option<&str>, swap_fee_bps: Option<i32>, swap_fee_token: Option<&str>, trade_surplus_recipient: Option<&str>, excluded_sources: Option<&str>) -> Result<models::GaslessGetQuote200Response, Error<GaslessGetQuoteError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/gasless/quote", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("chainId", &chain_id.to_string())]);
    local_var_req_builder = local_var_req_builder.query(&[("buyToken", &buy_token.to_string())]);
    local_var_req_builder = local_var_req_builder.query(&[("sellToken", &sell_token.to_string())]);
    local_var_req_builder = local_var_req_builder.query(&[("sellAmount", &sell_amount.to_string())]);
    local_var_req_builder = local_var_req_builder.query(&[("taker", &taker.to_string())]);
    if let Some(ref local_var_str) = swap_fee_recipient {
        local_var_req_builder = local_var_req_builder.query(&[("swapFeeRecipient", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = swap_fee_bps {
        local_var_req_builder = local_var_req_builder.query(&[("swapFeeBps", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = swap_fee_token {
        local_var_req_builder = local_var_req_builder.query(&[("swapFeeToken", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = trade_surplus_recipient {
        local_var_req_builder = local_var_req_builder.query(&[("tradeSurplusRecipient", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = excluded_sources {
        local_var_req_builder = local_var_req_builder.query(&[("excludedSources", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    local_var_req_builder = local_var_req_builder.header("0x-api-key", param_0x_api_key.to_string());
    if let Some(local_var_param_value) = param_0x_version {
        local_var_req_builder = local_var_req_builder.header("0x-version", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GaslessGetQuoteError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Get the status of a gasless swap
pub async fn gasless_get_status(configuration: &configuration::Configuration, param_0x_api_key: &str, chain_id: i32, trade_hash: &str, param_0x_version: Option<&str>) -> Result<models::GaslessGetStatus200Response, Error<GaslessGetStatusError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/gasless/status/{tradeHash}", local_var_configuration.base_path, tradeHash=crate::apis::urlencode(trade_hash));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("chainId", &chain_id.to_string())]);
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    local_var_req_builder = local_var_req_builder.header("0x-api-key", param_0x_api_key.to_string());
    if let Some(local_var_param_value) = param_0x_version {
        local_var_req_builder = local_var_req_builder.header("0x-version", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GaslessGetStatusError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Submit a gasless swap
pub async fn gasless_submit(configuration: &configuration::Configuration, param_0x_api_key: &str, gasless_submit_request: models::GaslessSubmitRequest, param_0x_version: Option<&str>) -> Result<models::GaslessSubmit200Response, Error<GaslessSubmitError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/gasless/submit", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    local_var_req_builder = local_var_req_builder.header("0x-api-key", param_0x_api_key.to_string());
    if let Some(local_var_param_value) = param_0x_version {
        local_var_req_builder = local_var_req_builder.header("0x-version", local_var_param_value.to_string());
    }
    local_var_req_builder = local_var_req_builder.json(&gasless_submit_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GaslessSubmitError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

