/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GaslessSubmitRequestApprovalEip712AnyOf2Types {
    #[serde(rename = "EIP712Domain")]
    pub eip712_domain: Vec<models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712TypesValueInner>,
    #[serde(rename = "MetaTransaction")]
    pub meta_transaction: Vec<models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712TypesValueInner>,
}

impl GaslessSubmitRequestApprovalEip712AnyOf2Types {
    pub fn new(eip712_domain: Vec<models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712TypesValueInner>, meta_transaction: Vec<models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712TypesValueInner>) -> GaslessSubmitRequestApprovalEip712AnyOf2Types {
        GaslessSubmitRequestApprovalEip712AnyOf2Types {
            eip712_domain,
            meta_transaction,
        }
    }
}

