/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GaslessSubmitRequestApprovalEip712AnyOf2Message {
    #[serde(rename = "nonce")]
    pub nonce: f64,
    #[serde(rename = "from")]
    pub from: String,
    #[serde(rename = "functionSignature")]
    pub function_signature: String,
}

impl GaslessSubmitRequestApprovalEip712AnyOf2Message {
    pub fn new(nonce: f64, from: String, function_signature: String) -> GaslessSubmitRequestApprovalEip712AnyOf2Message {
        GaslessSubmitRequestApprovalEip712AnyOf2Message {
            nonce,
            from,
            function_signature,
        }
    }
}

