/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GaslessSubmitRequestApprovalEip712AnyOfMessage {
    #[serde(rename = "owner")]
    pub owner: String,
    #[serde(rename = "spender")]
    pub spender: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "nonce")]
    pub nonce: f64,
    #[serde(rename = "deadline")]
    pub deadline: String,
}

impl GaslessSubmitRequestApprovalEip712AnyOfMessage {
    pub fn new(owner: String, spender: String, value: String, nonce: f64, deadline: String) -> GaslessSubmitRequestApprovalEip712AnyOfMessage {
        GaslessSubmitRequestApprovalEip712AnyOfMessage {
            owner,
            spender,
            value,
            nonce,
            deadline,
        }
    }
}

