/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GaslessSubmitRequestTradeEip712 : The `trade.eip712` from the quote endpoint
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GaslessSubmitRequestTradeEip712 {
    #[serde(rename = "types")]
    pub types: std::collections::HashMap<String, Vec<models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712TypesValueInner>>,
    #[serde(rename = "primaryType")]
    pub primary_type: String,
    #[serde(rename = "domain")]
    pub domain: Box<models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712Domain>,
    #[serde(rename = "message")]
    pub message: Box<models::GaslessSubmitRequestTradeEip712Message>,
}

impl GaslessSubmitRequestTradeEip712 {
    /// The `trade.eip712` from the quote endpoint
    pub fn new(types: std::collections::HashMap<String, Vec<models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712TypesValueInner>>, primary_type: String, domain: models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712Domain, message: models::GaslessSubmitRequestTradeEip712Message) -> GaslessSubmitRequestTradeEip712 {
        GaslessSubmitRequestTradeEip712 {
            types,
            primary_type,
            domain: Box::new(domain),
            message: Box::new(message),
        }
    }
}

