/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GaslessSubmitRequestApprovalSignature {
    #[serde(rename = "signatureType")]
    pub signature_type: f64,
    #[serde(rename = "v")]
    pub v: f64,
    #[serde(rename = "r")]
    pub r: String,
    #[serde(rename = "s")]
    pub s: String,
}

impl GaslessSubmitRequestApprovalSignature {
    pub fn new(signature_type: f64, v: f64, r: String, s: String) -> GaslessSubmitRequestApprovalSignature {
        GaslessSubmitRequestApprovalSignature {
            signature_type,
            v,
            r,
            s,
        }
    }
}

