/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GaslessGetPrice200ResponseAnyOf {
    /// The block number at which the liquidity sources were sampled to generate the quote. This indicates the freshness of the quote
    #[serde(rename = "blockNumber")]
    pub block_number: Box<serde_json::Value>,
    /// The amount of `buyToken` (in `buyToken` units) that will be bought in the swap
    #[serde(rename = "buyAmount")]
    pub buy_amount: Box<serde_json::Value>,
    /// The contract address of the token to buy in the swap
    #[serde(rename = "buyToken")]
    pub buy_token: String,
    #[serde(rename = "fees")]
    pub fees: Box<models::SwapPermit2GetPrice200ResponseAnyOfFees>,
    #[serde(rename = "issues")]
    pub issues: Box<models::SwapPermit2GetPrice200ResponseAnyOfIssues>,
    /// This validates the availability of liquidity for the quote requested. The rest of the fields will only be returned if `true`
    #[serde(rename = "liquidityAvailable")]
    pub liquidity_available: bool,
    /// The price which must be met or else the entire transaction will revert. This price is influenced by the `slippageBps` parameter. On-chain sources may encounter price movements from quote to settlement
    #[serde(rename = "minBuyAmount")]
    pub min_buy_amount: Box<serde_json::Value>,
    #[serde(rename = "route")]
    pub route: Box<models::SwapPermit2GetPrice200ResponseAnyOfRoute>,
    /// The amount of `sellToken` (in `sellToken` units) that will be sold in this swap
    #[serde(rename = "sellAmount")]
    pub sell_amount: Box<serde_json::Value>,
    /// The contract address of the token to sell in the swap
    #[serde(rename = "sellToken")]
    pub sell_token: String,
    /// The address of the target contract that the transaction will be submitted to
    #[serde(rename = "target")]
    pub target: String,
    /// The unique ZeroEx identifier of the request
    #[serde(rename = "zid")]
    pub zid: String,
}

impl GaslessGetPrice200ResponseAnyOf {
    pub fn new(block_number: serde_json::Value, buy_amount: serde_json::Value, buy_token: String, fees: models::SwapPermit2GetPrice200ResponseAnyOfFees, issues: models::SwapPermit2GetPrice200ResponseAnyOfIssues, liquidity_available: bool, min_buy_amount: serde_json::Value, route: models::SwapPermit2GetPrice200ResponseAnyOfRoute, sell_amount: serde_json::Value, sell_token: String, target: String, zid: String) -> GaslessGetPrice200ResponseAnyOf {
        GaslessGetPrice200ResponseAnyOf {
            block_number: Box::new(block_number),
            buy_amount: Box::new(buy_amount),
            buy_token,
            fees: Box::new(fees),
            issues: Box::new(issues),
            liquidity_available,
            min_buy_amount: Box::new(min_buy_amount),
            route: Box::new(route),
            sell_amount: Box::new(sell_amount),
            sell_token,
            target,
            zid,
        }
    }
}

