/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GaslessSubmitRequestApprovalEip712AnyOf1Message {
    #[serde(rename = "holder")]
    pub holder: String,
    #[serde(rename = "spender")]
    pub spender: String,
    #[serde(rename = "nonce")]
    pub nonce: f64,
    #[serde(rename = "expiry")]
    pub expiry: String,
    #[serde(rename = "allowed")]
    pub allowed: bool,
}

impl GaslessSubmitRequestApprovalEip712AnyOf1Message {
    pub fn new(holder: String, spender: String, nonce: f64, expiry: String, allowed: bool) -> GaslessSubmitRequestApprovalEip712AnyOf1Message {
        GaslessSubmitRequestApprovalEip712AnyOf1Message {
            holder,
            spender,
            nonce,
            expiry,
            allowed,
        }
    }
}

