/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GaslessSubmitRequest {
    /// Chain ID. See [here](https://0x.org/docs/next/developer-resources/supported-chains) for the list of supported chains
    #[serde(rename = "chainId")]
    pub chain_id: i32,
    #[serde(rename = "approval", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub approval: Option<Option<Box<models::GaslessSubmitRequestApproval>>>,
    #[serde(rename = "trade")]
    pub trade: Box<models::GaslessSubmitRequestTrade>,
}

impl GaslessSubmitRequest {
    pub fn new(chain_id: i32, trade: models::GaslessSubmitRequestTrade) -> GaslessSubmitRequest {
        GaslessSubmitRequest {
            chain_id,
            approval: None,
            trade: Box::new(trade),
        }
    }
}

