/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GaslessGetQuote200ResponseAnyOfTradeEip712 : This is the necessary data for [EIP-712](https://eips.ethereum.org/EIPS/eip-712). Please don't assume static shapes for `trade.eip712.types`, `trade.eip712.domain`, `trade.eip712.primaryType` and `trade.eip712.message` as they will change depending on the `type`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GaslessGetQuote200ResponseAnyOfTradeEip712 {
    #[serde(rename = "types")]
    pub types: std::collections::HashMap<String, Vec<models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712TypesValueInner>>,
    #[serde(rename = "domain")]
    pub domain: Box<models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712Domain>,
    #[serde(rename = "message")]
    pub message: std::collections::HashMap<String, models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712MessageValue>,
    #[serde(rename = "primaryType")]
    pub primary_type: String,
}

impl GaslessGetQuote200ResponseAnyOfTradeEip712 {
    /// This is the necessary data for [EIP-712](https://eips.ethereum.org/EIPS/eip-712). Please don't assume static shapes for `trade.eip712.types`, `trade.eip712.domain`, `trade.eip712.primaryType` and `trade.eip712.message` as they will change depending on the `type`
    pub fn new(types: std::collections::HashMap<String, Vec<models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712TypesValueInner>>, domain: models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712Domain, message: std::collections::HashMap<String, models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712MessageValue>, primary_type: String) -> GaslessGetQuote200ResponseAnyOfTradeEip712 {
        GaslessGetQuote200ResponseAnyOfTradeEip712 {
            types,
            domain: Box::new(domain),
            message,
            primary_type,
        }
    }
}

