/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GaslessGetStatus200ResponseAnyOfApprovalTransactionsInner {
    /// The onchain transaction hash
    #[serde(rename = "hash")]
    pub hash: String,
    /// The timestamp when the transaction was submitted onchain
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
}

impl GaslessGetStatus200ResponseAnyOfApprovalTransactionsInner {
    pub fn new(hash: String, timestamp: i32) -> GaslessGetStatus200ResponseAnyOfApprovalTransactionsInner {
        GaslessGetStatus200ResponseAnyOfApprovalTransactionsInner {
            hash,
            timestamp,
        }
    }
}

