/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsufficientBalanceOrAllowanceData {
    /// The unique ZeroEx identifier of the request
    #[serde(rename = "zid")]
    pub zid: String,
    /// The hash of the meta-transaction provided by the caller
    #[serde(rename = "metaTransactionHash")]
    pub meta_transaction_hash: String,
    /// The intended signer of the meta-transaction
    #[serde(rename = "taker")]
    pub taker: String,
    /// The sell token
    #[serde(rename = "sellToken")]
    pub sell_token: String,
    /// The sell amount
    #[serde(rename = "sellAmount")]
    pub sell_amount: Box<serde_json::Value>,
    /// The smaller value of the balance or the allowance of the taker
    #[serde(rename = "minBalanceOrAllowance")]
    pub min_balance_or_allowance: Box<serde_json::Value>,
}

impl InsufficientBalanceOrAllowanceData {
    pub fn new(zid: String, meta_transaction_hash: String, taker: String, sell_token: String, sell_amount: serde_json::Value, min_balance_or_allowance: serde_json::Value) -> InsufficientBalanceOrAllowanceData {
        InsufficientBalanceOrAllowanceData {
            zid,
            meta_transaction_hash,
            taker,
            sell_token,
            sell_amount: Box::new(sell_amount),
            min_balance_or_allowance: Box::new(min_balance_or_allowance),
        }
    }
}

