/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsufficientBalanceData {
    /// The unique ZeroEx identifier of the request
    #[serde(rename = "zid")]
    pub zid: String,
    /// The taker of the transaction
    #[serde(rename = "taker")]
    pub taker: String,
    /// The sell token
    #[serde(rename = "sellToken")]
    pub sell_token: String,
    /// The sell amount
    #[serde(rename = "sellAmount")]
    pub sell_amount: Box<serde_json::Value>,
    /// The current balance of the taker for the sell token
    #[serde(rename = "balance")]
    pub balance: Box<serde_json::Value>,
}

impl InsufficientBalanceData {
    pub fn new(zid: String, taker: String, sell_token: String, sell_amount: serde_json::Value, balance: serde_json::Value) -> InsufficientBalanceData {
        InsufficientBalanceData {
            zid,
            taker,
            sell_token,
            sell_amount: Box::new(sell_amount),
            balance: Box::new(balance),
        }
    }
}

