/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidSignerData {
    /// The unique ZeroEx identifier of the request
    #[serde(rename = "zid")]
    pub zid: String,
    /// The hash of the meta-transaction provided by the caller
    #[serde(rename = "metaTransactionHash")]
    pub meta_transaction_hash: String,
    /// The intended signer of the meta-transaction
    #[serde(rename = "taker")]
    pub taker: String,
    /// The signer of the meta-transaction
    #[serde(rename = "signer")]
    pub signer: String,
}

impl InvalidSignerData {
    pub fn new(zid: String, meta_transaction_hash: String, taker: String, signer: String) -> InvalidSignerData {
        InvalidSignerData {
            zid,
            meta_transaction_hash,
            taker,
            signer,
        }
    }
}

