/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetaTransactionExpiryTooSoonData {
    /// The unique ZeroEx identifier of the request
    #[serde(rename = "zid")]
    pub zid: String,
    /// The hash of the meta-transaction provided by the caller
    #[serde(rename = "metaTransactionHash")]
    pub meta_transaction_hash: String,
    /// The expiry of the meta-transaction provided by the caller in ms
    #[serde(rename = "expiry")]
    pub expiry: Box<serde_json::Value>,
}

impl MetaTransactionExpiryTooSoonData {
    pub fn new(zid: String, meta_transaction_hash: String, expiry: serde_json::Value) -> MetaTransactionExpiryTooSoonData {
        MetaTransactionExpiryTooSoonData {
            zid,
            meta_transaction_hash,
            expiry: Box::new(expiry),
        }
    }
}

