/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PendingTradesAlreadyExistData {
    /// The unique ZeroEx identifier of the request
    #[serde(rename = "zid")]
    pub zid: String,
    /// The hash of the meta-transaction provided by the caller
    #[serde(rename = "metaTransactionHash")]
    pub meta_transaction_hash: String,
    /// The list of pending meta-transaction hashes for the same taker and sell token
    #[serde(rename = "pendingMetaTransactionHashes")]
    pub pending_meta_transaction_hashes: Vec<String>,
}

impl PendingTradesAlreadyExistData {
    pub fn new(zid: String, meta_transaction_hash: String, pending_meta_transaction_hashes: Vec<String>) -> PendingTradesAlreadyExistData {
        PendingTradesAlreadyExistData {
            zid,
            meta_transaction_hash,
            pending_meta_transaction_hashes,
        }
    }
}

