/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SourcesGetSources200Response {
    /// The array of liquidity sources aggregated by 0x for the requested chain
    #[serde(rename = "sources")]
    pub sources: Vec<String>,
    /// The unique ZeroEx identifier of the request
    #[serde(rename = "zid")]
    pub zid: String,
}

impl SourcesGetSources200Response {
    pub fn new(sources: Vec<String>, zid: String) -> SourcesGetSources200Response {
        SourcesGetSources200Response {
            sources,
            zid,
        }
    }
}

