/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SwapPermit2GetQuote200Response {
    /// The block number at which the liquidity sources were sampled to generate the quote. This indicates the freshness of the quote
    #[serde(rename = "blockNumber")]
    pub block_number: Box<serde_json::Value>,
    /// The amount of `buyToken` (in `buyToken` units) that will be bought in the swap
    #[serde(rename = "buyAmount")]
    pub buy_amount: Box<serde_json::Value>,
    /// The contract address of the token to buy in the swap
    #[serde(rename = "buyToken")]
    pub buy_token: String,
    #[serde(rename = "fees")]
    pub fees: Box<models::SwapPermit2GetQuote200ResponseAnyOfFees>,
    #[serde(rename = "issues")]
    pub issues: Box<models::SwapPermit2GetPrice200ResponseAnyOfIssues>,
    /// This validates the availability of liquidity for the quote requested. No other fields will be returned if it is `false`
    #[serde(rename = "liquidityAvailable")]
    pub liquidity_available: bool,
    /// The price which must be met or else the transaction will revert. This price is influenced by the `slippageBps` parameter. On-chain sources may encounter price movements from quote to settlement
    #[serde(rename = "minBuyAmount")]
    pub min_buy_amount: Box<serde_json::Value>,
    #[serde(rename = "permit2", deserialize_with = "Option::deserialize")]
    pub permit2: Option<Box<models::SwapPermit2GetQuote200ResponseAnyOfPermit2>>,
    #[serde(rename = "route")]
    pub route: Box<models::SwapPermit2GetPrice200ResponseAnyOfRoute>,
    /// The amount of `sellToken` (in `sellToken` units) that will be sold in this swap
    #[serde(rename = "sellAmount")]
    pub sell_amount: Box<serde_json::Value>,
    /// The contract address of the token to sell in the swap
    #[serde(rename = "sellToken")]
    pub sell_token: String,
    /// The estimated total network cost of the swap. On chains where they is no L1 data cost, it is calculated as `gas` * `gasPrice. On chains where there is an L1 data cost, it is calculated as `gas` * `gasPrice + L1 data
    #[serde(rename = "totalNetworkFee", deserialize_with = "Option::deserialize")]
    pub total_network_fee: Option<Box<serde_json::Value>>,
    #[serde(rename = "transaction")]
    pub transaction: Box<models::SwapPermit2GetQuote200ResponseAnyOfTransaction>,
    /// The unique ZeroEx identifier of the request
    #[serde(rename = "zid")]
    pub zid: String,
}

impl SwapPermit2GetQuote200Response {
    pub fn new(block_number: serde_json::Value, buy_amount: serde_json::Value, buy_token: String, fees: models::SwapPermit2GetQuote200ResponseAnyOfFees, issues: models::SwapPermit2GetPrice200ResponseAnyOfIssues, liquidity_available: bool, min_buy_amount: serde_json::Value, permit2: Option<models::SwapPermit2GetQuote200ResponseAnyOfPermit2>, route: models::SwapPermit2GetPrice200ResponseAnyOfRoute, sell_amount: serde_json::Value, sell_token: String, total_network_fee: Option<serde_json::Value>, transaction: models::SwapPermit2GetQuote200ResponseAnyOfTransaction, zid: String) -> SwapPermit2GetQuote200Response {
        SwapPermit2GetQuote200Response {
            block_number: Box::new(block_number),
            buy_amount: Box::new(buy_amount),
            buy_token,
            fees: Box::new(fees),
            issues: Box::new(issues),
            liquidity_available,
            min_buy_amount: Box::new(min_buy_amount),
            permit2: if let Some(x) = permit2 {Some(Box::new(x))} else {None},
            route: Box::new(route),
            sell_amount: Box::new(sell_amount),
            sell_token,
            total_network_fee: if let Some(x) = total_network_fee {Some(Box::new(x))} else {None},
            transaction: Box::new(transaction),
            zid,
        }
    }
}

