/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712Domain {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "chainId", skip_serializing_if = "Option::is_none")]
    pub chain_id: Option<i32>,
    #[serde(rename = "verifyingContract", skip_serializing_if = "Option::is_none")]
    pub verifying_contract: Option<String>,
    #[serde(rename = "salt", skip_serializing_if = "Option::is_none")]
    pub salt: Option<String>,
}

impl SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712Domain {
    pub fn new() -> SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712Domain {
        SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712Domain {
            name: None,
            version: None,
            chain_id: None,
            verifying_contract: None,
            salt: None,
        }
    }
}

