/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SwapPermit2GetQuote200ResponseAnyOfPermit2 : This is the approval object which contains the necessary fields to submit an approval for this transaction. Null if sell token is the native token or the transaction is a native token wrap / unwrap
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SwapPermit2GetQuote200ResponseAnyOfPermit2 {
    /// `Permit2`
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The hash for the approval according to [EIP-712](https://eips.ethereum.org/EIPS/eip-712). If you compute the hash from eip712 field, it should match the value of this field
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "eip712")]
    pub eip712: Box<models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712>,
}

impl SwapPermit2GetQuote200ResponseAnyOfPermit2 {
    /// This is the approval object which contains the necessary fields to submit an approval for this transaction. Null if sell token is the native token or the transaction is a native token wrap / unwrap
    pub fn new(r#type: Type, hash: String, eip712: models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712) -> SwapPermit2GetQuote200ResponseAnyOfPermit2 {
        SwapPermit2GetQuote200ResponseAnyOfPermit2 {
            r#type,
            hash,
            eip712: Box::new(eip712),
        }
    }
}
/// `Permit2`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Permit2")]
    Permit2,
}

impl Default for Type {
    fn default() -> Type {
        Self::Permit2
    }
}

