/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SwapPermit2GetPrice200ResponseAnyOfRoute : The path of liquidity sources to be used in executing this swap
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SwapPermit2GetPrice200ResponseAnyOfRoute {
    /// Details of each segment that 0x routes the swap through
    #[serde(rename = "fills")]
    pub fills: Vec<models::SwapPermit2GetPrice200ResponseAnyOfRouteFillsInner>,
    /// Properties of the tokens involved in the swap
    #[serde(rename = "tokens")]
    pub tokens: Vec<models::SwapPermit2GetPrice200ResponseAnyOfRouteTokensInner>,
}

impl SwapPermit2GetPrice200ResponseAnyOfRoute {
    /// The path of liquidity sources to be used in executing this swap
    pub fn new(fills: Vec<models::SwapPermit2GetPrice200ResponseAnyOfRouteFillsInner>, tokens: Vec<models::SwapPermit2GetPrice200ResponseAnyOfRouteTokensInner>) -> SwapPermit2GetPrice200ResponseAnyOfRoute {
        SwapPermit2GetPrice200ResponseAnyOfRoute {
            fills,
            tokens,
        }
    }
}

