/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712TypesValueInner {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712TypesValueInner {
    pub fn new(name: String, r#type: String) -> SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712TypesValueInner {
        SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712TypesValueInner {
            name,
            r#type,
        }
    }
}

