/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712 : Necessary data for [EIP-712](https://eips.ethereum.org/EIPS/eip-712)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712 {
    #[serde(rename = "types")]
    pub types: std::collections::HashMap<String, Vec<models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712TypesValueInner>>,
    #[serde(rename = "domain")]
    pub domain: Box<models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712Domain>,
    #[serde(rename = "message")]
    pub message: std::collections::HashMap<String, models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712MessageValue>,
    #[serde(rename = "primaryType")]
    pub primary_type: String,
}

impl SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712 {
    /// Necessary data for [EIP-712](https://eips.ethereum.org/EIPS/eip-712)
    pub fn new(types: std::collections::HashMap<String, Vec<models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712TypesValueInner>>, domain: models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712Domain, message: std::collections::HashMap<String, models::SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712MessageValue>, primary_type: String) -> SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712 {
        SwapPermit2GetQuote200ResponseAnyOfPermit2Eip712 {
            types,
            domain: Box::new(domain),
            message,
            primary_type,
        }
    }
}

