/*
 * 0x API
 *
 * These are the API references for the beta version of 0x API v2. If you are looking for API v1 references, [see here](/0x-swap-api/api-references/overview).
 *
 * The version of the OpenAPI document: next
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SwapPermit2GetPrice200ResponseAnyOf1 {
    /// This validates the availability of liquidity for the quote requested. No other fields will be returned if it is `false`
    #[serde(rename = "liquidityAvailable")]
    pub liquidity_available: bool,
    /// The unique ZeroEx identifier of the request
    #[serde(rename = "zid")]
    pub zid: String,
}

impl SwapPermit2GetPrice200ResponseAnyOf1 {
    pub fn new(liquidity_available: bool, zid: String) -> SwapPermit2GetPrice200ResponseAnyOf1 {
        SwapPermit2GetPrice200ResponseAnyOf1 {
            liquidity_available,
            zid,
        }
    }
}

